#!/bin/bash
#
# This script generates new Blockchain skeleton files.

pushd codegen-v2
cargo run -- new-blockchain $1
popd # codegen-v2

pushd codegen
codegen/bin/newcoin-mobile-tests $1
popd # Update 0x9E5287e49ed26A5514AAe74A2362d048864B1aDA
